name: Build gh-pages
on:
  push:
    branches:
    - main
    - master
jobs:
  build-gh-pages:
    runs-on: ubuntu-latest      
    steps:
      - name: Manage branches
        uses: julb/action-manage-branch@v1
        with:
          name: gh-pages
          from: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm -rf .
          git commit --allow-empty -m "Build Reset"
          git push
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
      - run: |
          mv dist docs
          cd docs
          git fetch
          git checkout gh-pages
          git add .
          git commit -m "Build"
          git push

